export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const EXPAND_MENU = 'EXPAND_MENU'
export const SWITCH_EFFECT = 'SWITCH_EFFECT'
export const SET_USER = 'SET_USER'
export const SET_JWT = 'SET_JWT'
export const FORWARD_TO = 'FORWARD_TO'
export const SET_VERSION = 'SET_VERSION'
